{
 "title": "Jenkins cpu memory",
 "time": { "from": "2025-11-22T15:06:48.328Z", "to": "2025-11-22T15:23:21.662Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "default_jenkins_builds_available_builds_count{jenkins_job=\"project1\"}"
    }
   ]
  },
  {
   "title": "Jenkins: Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) \r\n/ node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Root Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100\r\n"
    }
   ]
  },
  {
   "title": "Jenkins: CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total[1m])) without (mode)\r\n"
    }
   ]
  },
  {
   "title": "Jenkins Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "jenkins_jobs_running_total\r\n" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}